"""Constants for the Delta Wallbox integration."""

DOMAIN = "delta_wallbox"

# Configuration
CONF_IP_ADDRESS = "ip_address"
CONF_PORT = "port"
CONF_SLAVE_ID = "slave_id"

DEFAULT_PORT = 502
DEFAULT_SCAN_INTERVAL = 600

# Modbus Registers
REG_CHARGER_STATE = 100
# REG_CHARGER_VERSION = 101
# REG_EVSE_COUNT = 102
# REG_CHARGER_ERROR = 103
REG_CHARGER_SERIAL_NUMBER = 110
# REG_CHARGER_MODEL = 130

# REG_STATE = 0
# REG_CHARGE_STATE = 1
# REG_VOLTAGE = 3
# REG_CHARGING_POWER = 5
# REG_CURRENT = 7
# REG_POWER = 9
# REG_SOC = 11
# REG_MAX_CHARGING_POWER = 13
# REG_MIN_CHARGING_POWER = 15
# REG_CHARGING_TIME = 17
# REG_CHARGED_ENERGY = 19
# REG_DISCHARGED_ENERGY = 21
# REG_MIN_CHARGING_POWER_REQUIRED = 39
# REG_CURRENT_POWER_CONSUMPTION_TOTAL = 47
# REG_EVSE_ERROR_CODE = 55
# REG_TOTAL_BATTERY_CAPACITY = 59
# REG_RFID = 100


# Writable Registers
REG_SET_POWER_LIMIT = 1
REG_START_STOP_CHARGING = 3
REG_COMM_TIMEOUT_ENABLE = 201
REG_COMM_TIMEOUT = 202
REG_FALLBACK_POWER = 203