"""Constants for the Delta Wallbox integration."""

DOMAIN = "delta_wallbox"

# Configuration
CONF_IP_ADDRESS = "ip_address"
CONF_PORT = "port"
CONF_SLAVE_ID = "slave_id"

DEFAULT_PORT = 502
DEFAULT_SCAN_INTERVAL = 600

# Modbus Registers
REG_CHARGER_STATE = 100
REG_EVSE_COUNT = 102
REG_SERIAL_NUMBER = 110
REG_MODEL = 130

REG_EVSE_STATE = 1
REG_EV_CONNECTED = 2
REG_CHARGING_TIME = 3
REG_CHARGING_POWER = 5
REG_CHARGED_ENERGY = 7
REG_SOC = 11
REG_EV_MAX_POWER = 13
REG_EV_MIN_POWER = 15
REG_P1_VOLTAGE = 17
REG_P2_VOLTAGE = 19
REG_P3_VOLTAGE = 21
REG_P1_CURRENT = 23
REG_P2_CURRENT = 25
REG_P3_CURRENT = 27
REG_GRID_FREQUENCY = 45
REG_GRID_TOTAL_POWER = 47
REG_GRID_P1_POWER = 49
REG_GRID_P2_POWER = 51
REG_GRID_P3_POWER = 53
REG_ERROR_CODE = 55

# Writable Registers
REG_SET_POWER_LIMIT = 1
REG_START_STOP_CHARGING = 3
REG_COMM_TIMEOUT_ENABLE = 201
REG_COMM_TIMEOUT = 202
REG_FALLBACK_POWER = 203
